### ISSUE TITLE
UX Questionnaire

### ISSUE THREAD

**Issue by lshoffman1** [Chicago/design.chicago.gov#27]

**Comment by taitcha** [comment]
[UX Questionnaire.md.zip](https://github.com/Chicago/design-system/files/2206701/UX.Questionnaire.md.zip)

**Comment by taitcha** [comment]
Example: 
[UX Questionnaire for Chicago Design System.pdf](https://github.com/Chicago/design-system/files/2206702/UX.Questionnaire.for.Chicago.Design.System.pdf)

**Comment by taitcha** [comment]
18F user interview method card (related, but not exact match): https://methods.18f.gov/discover/stakeholder-and-user-interviews/
