### ISSUE TITLE
User Research

### ISSUE THREAD

**Issue by lshoffman1** [Chicago/design.chicago.gov#29]
-participatory design
-task analysis
-contextual inquiry
-journey mapping or service design

**Comment by taitcha** [comment]
Task flow analysis: https://methods.18f.gov/decide/task-flow-analysis/
contextual inquiry: https://methods.18f.gov/discover/contextual-inquiry/
Service design tools: http://www.servicedesigntools.org/
Journey mapping: https://methods.18f.gov/decide/journey-mapping/
