### ISSUE TITLE
User Personas

### ISSUE THREAD

**Issue by lshoffman1** [Chicago/design.chicago.gov#32]

**Comment by taitcha** [comment]
Figma template: https://www.figma.com/file/KXyOex2lUeb2BxK3EecRdDM6/User_Persona?node-id=0%3A1

**Comment by dekdekdek** [comment]
https://xtensio.com/user-persona/

**Comment by jdkunesh** [comment]
18f card: https://methods.18f.gov/decide/personas/

**Comment by tomschenkjr** [comment]
To the extent it's useful, Sunlight Foundation has done [some documentation of Madion, Wisconsin user personas](http://sunlightfoundation.com/wp-content/uploads/2018/01/user-personas-and-journeys-madison-wi.pdf) and [are collecting additional personas](https://sunlightfoundation.com/2018/06/15/were-collecting-user-personas-for-open-data-send-us-yours/).
