### ISSUE TITLE
Product Review

### ISSUE THREAD

**Issue by lshoffman1** [Chicago/design.chicago.gov#41]
-Cognitive Walkthrough
-Heuristic Evaulation
-Competitive Analysis
-Accessibility Evaluation
-Content Patterns

**Comment by taitcha** [comment]
18F method cards:
Cognitive walkthrough: https://methods.18f.gov/discover/cognitive-walkthrough/
-Heuristic: https://methods.18f.gov/discover/heuristic-evaluation/
-Competitive: https://methods.18f.gov/decide/comparative-analysis/
-Patterns: https://methods.18f.gov/make/design-pattern-library/
