### ISSUE TITLE
User Research

### ISSUE THREAD

**Issue by lshoffman1** [Chicago/design.chicago.gov#42]
-Usability Testing

**Comment by dekdekdek** [comment]
https://airtable.com/templates/product-design-and-ux/expwA47rLvwTu3SiF/user-studies

**Comment by taitcha** [comment]
User interviews: https://methods.18f.gov/discover/stakeholder-and-user-interviews/

Contextual inquiry: https://methods.18f.gov/discover/contextual-inquiry/

**Comment by dekdekdek** [comment]
Prototyping: https://methods.18f.gov/make/prototyping/

**Comment by dekdekdek** [comment]
User surveys: https://www.usability.gov/how-to-and-tools/methods/online-surveys.html
