### ISSUE TITLE
https://design.chicago.gov/all has markdown in last section 

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design.chicago.gov#56]
the include is in markdown. this is why the other ones were in html, @jdkunesh.

**Comment by chrisjcalderon** [comment]
adding 
#main-content {
	width: 100% !important;
}

to the css should resolve the issue

**Comment by jdkunesh** [comment]
Yes, I just can't figure out where that would apply? It's only in the
mobile tablet breakpoint.

**Comment by jdkunesh** [comment]
actually, both of these comments belong on https://github.com/Chicago/design.chicago.gov/issues/55

**Comment by chrisjcalderon** [comment]
I added it to the page layout for simplicity purposes and as a quick fix. I tested it on several pages and seems to be showing OK on mobile now.
