### ISSUE TITLE
Consideration of global header & footer elements for pay.cityofchicago.org

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design.chicago.gov#8]
Given the Chicago Design System's wireframe styling of header & footer elements, let's try applying them to pay.cityofchicago.org and seeing where the system fits and needs extension.

**Comment by taitcha** [comment]
Mastheads: https://docs.google.com/presentation/d/1vJ_Qe4Q58OVCnMth7QtwHNVx1oXGoAKq_j2JvalUO1g/edit#slide=id.g3c75d76520_1_35
